aristanetworks/vane

vane/nrfu_client.py

* nrfu_client.py : Added interactive prompts for initial nrfu setup
The other two file changes are the same as those in  https://github.com/aristanetworks/vane/pull/372. So if that PR has been approved and merged by the time you review this one then feel free to overlook those and only focus on nrfu_client logic.
To the logic around modularizing the functionality and also function name suggestions please :) 
https://github.com/aristanetworks/vane/issues/353
This is a pre-requisite PR: https://github.com/aristanetworks/vane/pull/372
The current PR has changes which are a part of the above PR as well. So we can decide how to merge.
- - [ ] Breaking change (fix or …

Added interactive prompts for NRFU testing 

---

vane/nrfu_client.py

* nrfu_client.py: added logic which accept either a device list.txt file or CVP as source of input for generating a duts.yaml file
https://github.com/aristanetworks/vane/issues/354
https://github.com/aristanetworks/vane/issues/355
https://github.com/aristanetworks/vane/issues/356
https://github.com/aristanetworks/vane/issues/357
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
In development feature, will add test cases once feature is completed and behaves as is expected
- - [X] Pass
- …

Successfully generating the duts.yaml file

---

vane/nrfu_client.py

* File 1 and corresponding changes
* File 2 and corresponding changes
- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If applicable, ensure …

Generated definitions file for nrfu test cases

---

pyproject.toml
vane/nrfu_client.py
vane/vane_cli.py

* File 1 and corresponding changes
* File 2 and corresponding changes
- - [ ] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If applicable, ensure …

Run Vane with generated definitions and duts file

---

nrfu_tests/conftest.py

* Initialised the vane/nrfu_tests folder with empty files for
* master_def.yaml : the contents of which will be filled during test case development
* test_definition.yaml.j2 :  the contents of which will be filled during test case development
definitions_nrfu.yaml : the contents of this will get generated when nrfu client is executed
duts_nrfu.yaml : the contents of this will get generated when nrfu client is executed
* added conftest.py for fixtures to be available in this folder
https://github.com/aristanetworks/vane/issues/361
- - [ ] This change requires a …

Setup vane/nrfu_tests folder with initial files

---

install_vane.sh

* install_vane.sh 
https://github.com/aristanetworks/vane/issues/351
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Tested locally on (MacOS) and on docker images of CentOS and Debian systems. Vane runs successfully on each of these.
- - [X] Pass
- - [ ] Fail
If applicable, ensure documentation has been updated for ReadMe, Getting Started guide, and Style guide
Have handled the suggestions from the team after our review session in this PR

Added installation script for Vane

---

README.md

* README- changed minor phrasing as discussed yesterday
- - [X] Other : Documentation
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [X] Pass
- - [ ] Fail

Updated minor phrasing in README

---

sample_network_tests/conftest.py

* conftest.py: Handled pylint warnings
https://github.com/aristanetworks/vane/issues/460
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Test cases run correctly
- - [X] Pass
- - [ ] Fail

Refactored conftest.py in sample_network_tests

---

sample_network_tests/memory/test_memory.py
tests/unittests/test_tests_client.py
vane/logger.py
vane/test_case_logger.py
vane/tests_client.py
vane/vane_logging.py

* logger.py: changed the logic here from creating a single common logger for all test cases to creating a logger per test case passed to the setup_logger function
* vane_logging.py: changed location of vane.log to also be within logs folder
* tests_client.py: added a remove_test_case_logs method which deletes the old test case logs at the start of a vane run. Also made a change with respect to the remove_test_results_dir, as realized the location was hard coded there, now reading it from the definitions file instead.
* test_memory.py: sample test case using new logger
* test_tests_client.py: added test case coverage
logger.py: handling of per test case logger
https://github.com/aristanetworks/vane/issues/346
@kgrozis-arista you wanted me to update the style guide or the getting started …

Logging in Vane test cases to go to separate log files

---

tests/unittests/fixtures/expected_test_api.md
tests/unittests/fixtures/expected_test_host.json
tests/unittests/fixtures/expected_test_host.md
tests/unittests/fixtures/expected_test_host_no_steps.md
tests/unittests/test_tests_client.py
tests/unittests/test_tests_step_client.py
vane/report_client.py
vane/test_step_client.py
vane/tests_client.py
vane/utils.py

vane/tests_client.py - create self contained html file if self contained option is specified in the definitions.yaml
Other changes - the date timestamp of html file now exactly matches docx file.  
None 
#378 
- - [X] This change requires a documentation update
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Ensure current test cases pass and include newer test cases if …

Issue #378: html self contained changes

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_interfaces_mlag_status_check.py

Describe the solution you'd like
PyTest-CVP MLAG status check test case should have the following:
Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test case should be skipped if MLAG is not configured
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, interfaces
Use Test ID: NRFU2.4
From the output of  **show mlag**,  verified that the mlag status is displayed.
https://github.com/aristanetworks/vane/issues/426
- - [x] Other …

Issue-426:Convert Pytest-CVP MLAG status check test case to Vane #426

---

nrfu_tests/test_base_services_redundancy_sso_test.py
nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2

* test_definition.yaml: Updated test def with testcase NRFU1.3.
* test_definition.yaml.j2: Updated J2 with testcase NRFU1.3.
* test_base_services_redundancy_sso_test.py: Added python file for testcase NRFU1.3.
#421 
- - [x] Other (NRFU Testcase)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Note: **Tested the test case using the hardcoded output as this testcase is not working on the ACT lab and also on the …

Issue-421: Convert Pytest-CVP SSO test case to Vane

---

sample_network_tests/aaa/test_aaa.py
sample_network_tests/api/test_api.py
sample_network_tests/cpu/test_cpu.py
sample_network_tests/daemon/test_daemon.py
sample_network_tests/dns/test_dns.py
sample_network_tests/environment/test_environment.py
sample_network_tests/extension/test_extension.py
sample_network_tests/filesystem/test_filesystem.py
sample_network_tests/host/test_host.py
sample_network_tests/interface/test_interface.py
sample_network_tests/lldp/test_lldp.py
sample_network_tests/log/test_logging.py
sample_network_tests/memory/test_memory.py
sample_network_tests/ntp/test_ntp.py
sample_network_tests/system/test_system.py
sample_network_tests/tacacs/test_tacacs.py
sample_network_tests/users/test_users.py
sample_network_tests/vane_system_tests/test_vane.py
sample_network_tests/ztp/test_ztp.py

* sample_network_tests -> imports new logger, black formatting
https://github.com/aristanetworks/vane/issues/517
- - [X] Other : Refactor
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Logs get created for test case
- - [X] Pass
- - [ ] Fail

Refactored logging import in Sample Network Tests

---

nrfu_tests/master_def.yaml
nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_system_hardware_inventory.py

Converted the testcase as per the vane styling guide with the following changes in the below files:
*  test_definition.yaml: Updated test definition with testcase contents
* test_definition.yaml.j2: Updated the J2 file with the testcase steps
* test_system_hardware_inventory.py: Added the testcase file for inventory testcase.
From the output of the show command, verified that the card slots are inserted and present on the devices.
#447 
- - [ ] This change …

Issue-447: Testcase for Convert Pytest-CVP Inventory test case to Vane

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_system_hardware_free_memory.py

test_definition.yaml.j2: Updated J2 with testcase NRFU6.7
master_def.yaml: Updated master def with testcase NRFU6.7
test_definition.yaml: Added test def with testcase NRFU6.7
test_system_hardware_free_memory.py: Added python file for testcase NRFU6.7
This testcase will verify the memory utilization of the device. If the memory utilization is greater than expected then testcase should failed otherwise testcase should pass.
https://github.com/aristanetworks/vane/issues/446
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work …

Issue-446:Convert Pytest-CVP Free Memory test case to Vane

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_password_enable_functionality.py
nrfu_tests/test_security_rp_enable_pw.py

* master_def.yaml
Updated master def for testcase NRFU5.2
* test_definition.yaml.j2
Updated j2 file for testcase NRFU5.2
* test_definition.yaml
Updated test def for testcase NRFU5.2
* test_password_enable_functionality.py
Added python file for testcase NRFU5.2
This testcase will check if output starts with 'enable password' then testcase will pass 
and if output is not found then testcase will fail with output message.
https://github.com/aristanetworks/vane/issues/453
- - [x] Other (Convert PyTest-CVP Enable …

Issue-453 Convert Pytest-CVP Enable Password test case to Vane

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_system_hardware_temperature.py

test_definition.yaml: Updated test def with testcase NRFU6.11
test_definition.yaml.j2: Updated J2 with testcase NRFU6.11
master_def.yaml: Updated master def with testcase NRFU6.11
test_syslog_functionality.py: Added python file for testcase NRFU6.11
validating system temperature sensors details
#450 
- - [X] Other (NRFU testcases)
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Unit tests and report :
Pass Report:
1.  pass report ( pass without j2 )
[without_j2.docx](https://github.com/aristanetworks/vane/files/126074 …

Issue-450: Convert Pytest-CVP Hardware Temperature test case to Vane

---

nrfu_tests/test_security_rp_ssh_access_list.py

test_security_rp_ssh_access_list.py: Updated the logger changes
None
#525 
- - [x] Other (Updated the logger for testcase NRFU5.6)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
1. Testcase passed with all correct details.
Reports: [report_2309211657.docx](https://github.com/aristanetworks/vane/files/12697270/report_2309211657.docx)
[report_2309211656.zip](https://github.com/aristanetworks/vane/files/12697275/report_2309211656.zip)
2. Testcase fail in case SSHD enabled on one of the vrf but ACL is not configured. …

issue-525: Updated the logger for NRFU5.6

---

nrfu_tests/master_def.yaml

* nrfu_tests/master_def.yaml
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
test_definitions.yaml file does not get hard coded dut filter now
- - [X] Pass
- - [ ] Fail

Commenting out dut filter for example usage

---

nrfu_tests/master_def.yaml
nrfu_tests/test_bad_syslog_events.py
nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_system_hardware_bad_syslog_event.py

Describe the solution you'd like
PyTest-CVP Bad SysLog test case should have the following:
Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test case should be skipped if SysLog is not configured
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, system
Use Test ID: NRFU6.1
From the output of  **show logging last <daysOfLogs> days**,  verified the key words in syslog events that are generally considered to be bad
https://github.com/aristanetworks/vane/issues/440
- - [ ] This …

issue_440: Convert Pytest-CVP Bad SysLog test case to Vane

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_definition.yaml.j2
nrfu_tests/test_security_rp_telnet_disabled.py

Converted test_base_services_ntp_association.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU5.7
test_definition.yaml.j2: Updated J2 with testcase NRFU5.7
nrfu_tests/nrfu_tests/test_security_rp_telnet_disabled.py: Added testcase for NRFU5.7
From the output of  'show management telnet' or 'show management telnet vrf <vrf name>',  Verified that the the TELNET state is disabled for all the VRFs on DUT. 
#438 
- - [x] Other (NRFU …

Issue_438: Convert Pytest-CVP Telnet Disabled test case to Vane

---

tests/unittests/fixtures/definitions_nrfu_custom_expected.yaml
tests/unittests/fixtures/definitions_nrfu_default_expected.yaml
vane/nrfu_client.py

* vane/nrfu_client.py
None
Make NRFU HTML reports self contained #546
NOne
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Ran NRFU tests and verified the definitions file is correctly generated.
Yes
- - [x] Pass
- - [ ] Fail
None

Added self_contained to NRFU definitions

---

vane/report_client.py

* vane/report_client.py: Added table caching and implemented table caching for summary test case table.  Improved performance for large tables.
Docx table creation is slow for large tables #553
- - [ ] Easy
- - [x] Medium
- - [ ] Hard 
Verified changes against multiple test suites.  Test case continue to pass with improved performance
- - [x] Pass
- - [ ] Fail

Added table caching to improve performance

---

pyproject.toml
pytest.ini
setup.py
tests/unittests/conftest.py
tests/unittests/fixtures/host/test_host.py
tests/unittests/test_report.py
tests/unittests/test_tests_step_client.py
vane/report_client.py

- pyproject.toml change needed to run install using pip command
- pytest.ini change specifies the unit test paths
- setup.py needed to run `python setup.py ...` cmds specified in the #530 
- report_client.py - change needed to mitigate directory does not exist error
- rest of the files are changed to fix unit test errors
- pyproject.toml change please see if its correct.
- 
#530 
- - [ ] Other (please …

Issue #530 : Add setup.py, change pyproject.toml, pytest.ini and fix unit test failures

---

sample_network_tests/vane_system_tests/test_definition.yaml
sample_network_tests/vane_system_tests/test_vane.py
tests/unittests/test_tests_tools.py
vane/report_client.py
vane/tests_tools.py

* sample_network_tests/vane_system_tests/test_definition.yaml: Added test defintion for skip system test
* sample_network_tests/vane_system_tests/test_vane.py: Added skip system test
* vane/report_client.py: Modified to display skips in test case summary table and detailed test case reports
* vane/tests_tools.py: Modifed to add a skip variable to test object and add post processing skip logic
https://github.com/aristanetworks/vane/issues/486
- - [ ] Other (please …

Added skip functionality to framework

---

pyproject.toml
tests/unittests/test_report.py

* pyproject.toml -add dateutil
* tests/unittests/test_report.py - fix black and pylint issues
#537 
- - [] Bug fix (non-breaking change which fixes an issue)
- - [] New feature (non-breaking change which adds functionality)
add package required by tests to pyproject.toml and fix unit tests
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [x] Pass
- - [ ] Fail
If it fails, …

Issue #537: add dateutil and fix black and pylint issues

---

Dockerfile
Makefile

* Dockerfile - minor change to comment, no effect on file operation
* Makefile - rework targets that work on the dockerfile
* Create a CONTAINER_ENGINE variable that is set to docker, but can be changed to something like podman if the user is using a different engine
* Replace some other variables that directly reference docker with more generic 'container' variables
* Reduced the build targets to two targets that build the container and run the container, plus a third target that runs black on the vane directory using the built container. All other targets removed.
Now to use the Docker container, the set of commands is 
```
make container
```
to build the container, then
```
make run
```
to run the container. The container is expected to be run from within the Vane source directory, and …

Update makefile for docker container usage

---

vane/vane_cli.py

* vane_cli.py: added version flag
https://github.com/aristanetworks/vane/issues/540
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [X] Pass
- - [ ] Fail
To be tested with setup.py format as well

Added version flag to CLI

---

vane/report_client.py

* report_client.py: dut actual output json was getting print as fail/skip reason in test case summary. Corrected the incorrect assignment.
#628 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
BEFORE:
AFTER:
- - [X] Pass
- - [ ] Fail

[BUG FIX] Incorrect Reason for failure/skip 

---

.github/workflows/development-ci.yml

* .github/workflows/development-ci.yml
Adds a separate job named pip-install to test the pip installation process of Vane.
Installs Vane in the test environment using the `pip install` process, then runs several commands and verifies the output of those commands. Comments and steps in CI workflow should be self explanatory.
Verify if the test seems thorough as a test of the installation process
Fixes #534 
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Manual testing in CI pipeline
- - …

Verify pip install in development CI workflow

---

nrfu_tests/test_security_rp_ssh_access_list.py

Issue_59: Updated Marker typo for nrfu_tests/test_security_rp_ssh_access_list.py testcase
Updated  nrfu_tests/test_security_rp_ssh_access_list.py testcase with marker change as nrfu_test
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Before  and after the fix
- - [ ] Pass
- - [ ] Fail
If it fails, explain the …

Issue_59: Updated Marker typo for nrfu_tests/test_security_rp_ssh_access_list.py testcase

---

.github/workflows/development-ci.yml

development-ci.yml: changed the vane --help options to match current ones in develop
HOTFIX
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
pip-install now passes as seen in this PR
- - [X] Pass
- - [ ] Fail

Added version flag and removed environment flag for pip install change

---

nrfu_tests/test_misc_show_commands.py

* nrfu_tests/test_misc_show_commands.py
Changed logic to not fail on command failure.  Command is documented, but test case does not fail
NRFU3.1 - test_misc_show_commands broken #669
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [x] Pass
- - [ ] Fail

669 nrfu31 test misc show commands broken

---

nrfu_tests/test_system_hardware_inventory.py

* nrfu_tests/test_system_hardware_inventory.py
Commented out assertion since it is not working.  I will open a new issues for GSLabs to fix this.
NRFU6.8 - test_hardware_inventory_status #689
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Network Services verified
- - [x] Pass
- - [ ] Fail

689 nrfu68 test hardware inventory status

---

nrfu_tests/test_bad_syslog_events.py

* nrfu_tests/test_bad_syslog_events.py
Needed to change encoding to text for logging
https://github.com/aristanetworks/vane/issues/665
None
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
https://github.com/aristanetworks/ps-demos/actions/runs/8238235570
- - [x] Pass
- - [ ] Fail

Add encoding to show logging

---

nrfu_tests/test_interface_errors_and_discards.py

* nrfu_tests/test_interface_errors_and_discards.py
Need to make link status change more tolerant.  
NRFU2.3 - Change link status changes tolerance #662
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
https://github.com/aristanetworks/ps-demos/actions/runs/8235902095
- - [x] Pass
- - [ ] Fail

662 nrfu23 change link status changes tolerance

---

nrfu_tests/test_system_hardware_temperature.py

**Issue-Id: #707**
**NRFU6.11 Updated skip enhancement for nrfu_tests/test_system_hardware_temperature.py**
https://github.com/aristanetworks/vane/issues/707
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If it fails, explain the reason and …

Issue_707 NRFU6.11: Updated skip enhancement for nrfu_tests/test_system_hardware_temperature.py 

---

nrfu_tests/test_interfaces_port_channels.py

Updated skip enhancement: nrfu_tests/test_interfaces_port_channels
Skip test case with a valid reason and generate both docx and HTML reports
[Issue 714](https://github.com/aristanetworks/vane/issues/714)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
**Reports**
[pass_report.docx](https://github.com/aristanetworks/vane/files/14720052/pass_report.docx)
[skip_testcase.docx](https://github.com/aristanetworks/vane/files/14720053/skip_testcase.docx)
**HTML report**
[HTML …

Issue_714: NRFU2.6 Update skip enhancement: nrfu_tests/test_interfaces_port_channels

---

nrfu_tests/test_routing_bgp_evpn_peers_state.py

Updated nrfu_tests/test_routing_bgp_evpn_peers_state.py testcase with skip testcase enhancement
Skip test case with a valid reason and generate both docx and HTML reports with modification in show command.
[Issue 715](https://github.com/aristanetworks/vane/issues/715)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
**Reports**
[pass_report.docx](https://github.com/aristanetworks/vane/files/14721184/pass_report.docx)
[skip_test case.docx](https://github.com/aristanetworks/vane/files/14721 …

Issue_715: NRFU4.1 Update skip enhancement for test_routing_bgp_evpn_peers_state

---

nrfu_tests/test_system_hardware_power_supply_status.py

issue_708:Updated skip enhancement for nrfu_tests/test_system_hardware_power_supply_status.py(NRFU6.9)
* issue_708:Updated skip enhancement for nrfu_tests/test_system_hardware_power_supply_status.py(NRFU6.9)
NRFU6.9
https://github.com/aristanetworks/vane/issues/708
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Ensure current test cases pass …

issue_708: Updated skip enhancement(NRFU6.9) for nrfu_tests/test_system_hardware_power_supply_status.py

---

nrfu_tests/test_dns_base_services.py

*Updated skip enhancement for nrfu_tests/test_dns_base_services.py (NRFU1.1)
NRFU1.1
https://github.com/aristanetworks/vane/issues/712
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If it fails, explain the reason and whether or not we should …

issue_712: Updated skip enhancement(NRFU1.1) for nrfu_tests/test_dns_base_services.py

---

nrfu_tests/test_hardware_power_supply_voltage_status.py

* Updated test_hardware_power_supply_voltage_status.py testcase with skip enhancement (NRFU6.10)
https://github.com/aristanetworks/vane/issues/717
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail …

issue_717: NRFU6.10: Update skip enhancement nrfu_tests/test_hardware_power_supply_voltage_status.py

---

nrfu_tests/test_bad_syslog_events.py

issue_711:Updated nrfu_tests/test_bad_syslog_events.py with NRFU6.1 changes
NRFU6.1
https://github.com/aristanetworks/vane/issues/711
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If it fails, …

issue_711:Updated skip enhancement(NRFU6.1) for nrfu_tests/test_bad_syslog_events.py

---

nrfu_tests/test_definition.yaml
nrfu_tests/test_interfaces_mlag_status_check.py

* Updated nrfu_tests/test_definition.yaml with NRFU2.4 testcase changes
* Updated nrfu_tests/test_definition.yaml.j2 with NRFU2.4 testcase changes
https://github.com/aristanetworks/vane/issues/716
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] …

Issue_716 : NRFU2.4 : Update skip enhancement: nrfu_tests/test_interfaces_mlag_status_check.py

---

sample_network_tests/aaa/test_aaa.py
sample_network_tests/api/test_definition.yaml
sample_network_tests/cpu/test_definition.yaml
sample_network_tests/daemon/test_daemon.py
sample_network_tests/daemon/test_definition.yaml
sample_network_tests/dns/test_dns.py
sample_network_tests/environment/test_environment.py
sample_network_tests/host/test_definition.yaml
sample_network_tests/lldp/test_definition.yaml
sample_network_tests/tacacs/test_tacacs.py
sample_network_tests/users/test_users.py

Additionally added missing logging, and applied consistent dut filters for all test cases
* Missing logs
(1) test_environment.py
(2) test_tacacs.py
(3) test_users.py
* Incorrect object reference
(1) test_daemon.py: error being thrown in case of empty object, handled it accordingly
* Incorrect pasisng of arguments to api
(1) test_aaa.py
(2) test_dns.py
* Added skip logic
(1) test_environment.py
* Changed filters for test definitions to be consistent with Vane Demo Lab
(1) test_definition.yaml files for api, cpu, daemon, host, and lldp tests
test_daemon.py refactoring
#720 
Further issue created #725  for refactoring commands referenced in ntp, system, users, environment, log, and dns test case
Before closing #720 need to fix vane_system_tests using #727 as well
- - [X] Bug fix …

Refactored sample network test cases for errors in api calls

---

.github/workflows/build-site.yml
.github/workflows/release.yml
docs/requirements.txt
mkdocs.yaml
overrides/main.html
pyproject.toml

* build-site.yml: modified workflow to use mike to push to develop version of documentation
* release.yml: created workflow to create versioned documentation for newest release and point stable to newest version
* mkdocs.yml and pyproject.toml and requirements.txt: added mike plugin
* main.html: added html for displaying outdated warning when not on stable versioning of documentation
#740 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Locally deployed and tested
- - [X] Pass
- - [ ] …

Adding mike for documentation versioning

---

tests/unittests/test_vane_cli.py
vane/tests_client.py
vane/vane_cli.py

* vane_cli.py: added module to delete log files of unexecuted test cases based on output of .json report
* test_vane_cli.py: added unit test case for the same
Validating info from json report
#672 
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
- - [X] Pass
- - [ ] Fail

Added module to remove empty log files

---

docs/executing_vane/executing_vane.md

* executing_vane.md: added warning about logs and their cleaning
#672 
#732 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [X] Pass
- - [ ] Fail

added logs warning

---

tests/unittests/test_tests_client.py
tests/unittests/test_tests_tools.py
vane/report_client.py
vane/tests_client.py
vane/tests_tools.py

* tests_tools.py, report_client.py, tests_client.py: Refactored some logs which were printing json data and changed the messages to be more consistent
* Respective test files: tests_tests_tools.py, and test_tests_client.py to accommodate the above changes and unit tests to pass.
These 2 checks were redundant, if someone can validate that as well to ensure I didn't miss anything.
https://github.com/aristanetworks/vane/pull/599#discussion_r1382122442
https://github.com/aristanetworks/vane/pull/599#discussion_r1382122762
#557 
- - [ ] This change requires a …

Refactored logging in tests_tools, report_client and tests_client

---

.github/pull_request_template.md

* .github/pull_request_template.md : added information about testing and verifying documentation update
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [X] Pass
- - [ ] Fail

Update pull_request_template.md for documentation information

---

.github/workflows/build-site.yml
.github/workflows/release.yml
docs/requirements.txt
mkdocs.yaml
overrides/main.html
pyproject.toml

Same work as https://github.com/aristanetworks/vane/pull/744 which had approval

Added mike

---

.github/workflows/build-site.yml
.github/workflows/release.yml

Implemented fix for failing deployment via mike by referring to this issue: https://github.com/jimporter/mike/issues/60

Fixing deploy action using fetch-depth flag

---

vane/nrfu_client.py

* vane/nrfu_client.py
Closes #658 
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Manually ran `vane --nrfu` with all the options.
- - [x] Pass
- - [ ] Fail
If applicable, …

Issue #658: Print defaulting message in case user did not choose from available options

---

nrfu_tests/test_base_services_redundancy_sso_test.py

Skip enhancement: test_base_services_redundancy_sso_test.py(NRFU1.3)
* test_base_services_redundancy_sso_test.py: Updated the skip enhancement part for the test case
#718 
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
**Tested the test case on ACT for skip scenario 1 and used hardcoded output for pass and skip scenario 2.**
Pass Report: 
[report_2403271654.docx](https://github.com/aristanetworks/vane/files/14775777/report_2403271654.docx …

Issue-718: Skip enhancement: test_base_services_redundancy_sso_test.py(NRFU1.3)

---

vane/tests_tools.py

* Updated  vane/tests_tools.py with  generate_report utils 
Updated   vane/tests_tools.py   generate_report utils function,  set the default value for output argument so that older test cases won't get impacted with this change, and for new test cases, we will not pass the output as the argument.
https://github.com/aristanetworks/vane/issues/524
- - [x ] Easy
- - [ ] Medium
- - [ ] Hard 
Include before and after …

Issue_524:Output parameter from generate_report function can be removed

---

nrfu_tests/test_system_hardware_temperature.py

Description:Test Feature request for Vane NRFU Test 6.11 - Fine tuning for DCS-7010* and CCS-710P* platforms.
* test_system_hardware_temperature.py: Added enhancement changes in testcase NRFU6.11
Fine tuning for DCS-7010* and CCS-710P*
#760 
- - [ ] Easy
- - [x] Medium
- - [ ] Hard 
Tested on Hardcoded output.
Reports
[NRFU_760.zip](https://github.com/user-attachments/files/15526042/NRFU_760.zip)
Ensure current test cases …

issue_760: Test Feature request for Vane NRFU Test 6.11 - Fine tuning for DCS-7010* and CCS-710P* platforms
