- .github/workflows/cvp-extension-builder.yml
- Makefile
- resources/vane-bashrc
* resources/vane-bashrc - add steps to copy nrfu_tests to /vane-data in cvp container
* Makefile - fix VERSION extraction to gather data from pyproject.toml
The nrfu_tests folder is copied to the /vane-data directory just the same way the sample_network_tests folder is copied. The code is the exact same as the block above it but the folder being tested and copied is changed.
In the makefile, the VERSION had been extracted from the vane/\_\_init\_\_.py file, but that file is now dynamically filled from pyproject.toml, so the Makefile was giving errors in some of the steps that used the VERSION string. Fixed the extraction to pull the data from pyproject.toml instead.
No related issue
- - [X] New feature (non-breaking change which …
> Copy the nrfu_folder to the CVP container's /vane-data directory

- .github/workflows/cvp-extension-builder.yml
- resources/vane-bashrc
* resources/vane-bashrc - copy pytest.ini from vane project folder to /vane-data
Logic is the same as the preceding blocks in the container bashrc, except is checking for a file instead of directory, and copies the pytest.ini file if not found.
Fixes #470 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Built a new rpm package by temporarily adding the working branch to the workflow pipeline: https://github.com/aristanetworks/vane/actions/runs/5979088327
- - [X] Pass
- - [ ] Fail
If it …
> Add pytest.ini to vane-data folder in CVP container for RPM

- tests/unittests/test_tests_step_client.py
- vane/test_step_client.py
- vane/utils.py
* utils.py : Added now() function
* test_step_client : removed now() and referred to the now() in utils.py
* test_test_step_client.py : changed the mocking of now()
https://github.com/aristanetworks/vane/issues/455
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
tests for test_step_client pass as before
- - [X] Pass
- - [ ] Fail
> Moved now() to utils.py and changed the test function & test_step_client accordingly

- tests/unittests/test_tests_client.py
- vane/tests_client.py
- vane/utils.py
* tests_client.py: Changed the logic to generate .html files with different name (time stamp) so as to not overwrite existing .html file.
* test_tests_client.py: Refactored the test case accordingly
The naming of the reports
https://github.com/aristanetworks/vane/issues/376
https://github.com/aristanetworks/vane/pull/457 **SHOULD BE MERGED BEFORE** THIS PR
as it introduces the now() method in utils.py
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
All test cases pass:
The html results …
> Archiving HTML results

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_security_rp_eos_no_config_test.py
test_definition.yaml: Updated test def with testcase NRFU5.3
test_definition.yaml.j2: Updated J2 with testcase NRFU5.3
test_security_rp_eos_no_config_test.py: Added python file for testcase NRFU5.3
Running 'show lldp neighbors detail' command and verifying that localhost should not found on the LLDP neighbor information.
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Passed reports when test criteria met(no local host found in lldp details) …
> Added TC for NRFU5.3 LLDP neighbor functionality testcase

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_interfaces_port_channels.py
Converted test_interfaces_port_channels.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU2.6
test_definition.yaml.j2: Updated J2 with testcase NRFU2.6
nrfu_tests/test_interfaces_port_channels.py:  Added converted testsuite file for testcases NRFU2.6
From the output of  **show lacp interface all-ports**,  verified that the all port-channel interface members are collecting and distributing , if port channels are not found then testcase will skip.
https://github.com/aristanetworks/vane/issues/428
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as …
> Issue_428: Convert Pytest-CVP Port-Channel test case to Vane #428

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_system_hardware_coredump.py
* test_definition.yaml
Updated test def with testcase NRFU6.3.
* test_definition.yaml.j2 
Updated J2 with testcase NRFU6.3.
* master_def.yaml
Updated master def with testcase NRFU6.3.
* test_system_hardware_coredump.py
Added python file for testcase NRFU6.3.
Testcase check if core dump files found then fail it.
https://github.com/aristanetworks/vane/issues/442
- - [x] Other (Convert Pytest-CVP Core Dump test case to Vane)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
1. Testcase pass when no core dump files are …
> issue-442: Convert Pytest-CVP Core Dump test case to Vane

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_interfaces_errdisabled.py
test_definition.yaml: Updated test def with testcase NRFU2.2
test_definition.yaml.j2: Updated J2 with testcase NRFU2.2
test_interfaces_errdisabled.py: Added python file for testcase NRFU2.2
Running `show interfaces status errdisabled` command and verifying the no interface is in error disabled state.
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Passed report when none of the interface is in error disabled state.
[report_passed.docx](https://github.com/aristanetworks/vane/files/12607063/re …
> Issue_424 Added TC for NRFU2.2 interface status error disabled status

- nrfu_tests/master_def.yaml
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_interfaces_description_status.py
Converted test_interfaces_description_status.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU2.1
test_definition.yaml.j2: Updated J2 with testcase NRFU2.1
masterdef.yaml: Added master def yaml for DUTs
nrfu_tests/test_interfaces_description_status.py: Added converted testsuite file for testcases NRFU2.1
From the output of **show interfaces description**, verified that the all interface with description to verify having description and status as up, the interfaces with description to ignore having status as up, if interfaces or Vlans are not found then testcase will skip.
#423 
- - [ ] …
> Issue_423: Convert Pytest-CVP Interface Description test case to Vane #423

- nrfu_tests/test_base_services_ntp_association.py
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
Converted test_base_services_ntp_association.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU1.2
test_definition.yaml.j2: Updated J2 with testcase NRFU1.2.
nrfu_tests/test_base_services_ntp_association.py: Added testcase for NRFU1.2.
Verified primary and secondary associations using the output of `show ntp associations` command, if NTP server is not configured testcase will skip.
https://github.com/aristanetworks/vane/issues/420
- …
> issue_420: Converted Pytest-CVP NTP test case to Vane #420

- nrfu_tests/test_base_services_tacacs.py
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
Converted test_base_services_tacacs.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU1.4
test_definition.yaml.j2 and master_def.yaml : Updated J2 with testcase NRFU1.4
Verified TACACS servers have no errors, timeouts, failures or disconnects and test case should failed when No TACACS servers are configured on the device.
https://github.com/aristanetworks/vane/issues/422
- - [x] Other (nrfu_tests)
- - [ ] Easy
- - [x] Medium
- - [ ] …
> issue_422: Converted Pytest-CVP TACACS test case to Vane #422

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_security_rp_login_banner.py
CDescribe the solution you'd like
PyTest-CVP Login Banner test case should have the following:
Use Vane test case styling
Use Master definition file to simplify input
Add test case steps to the test case
Test should be added to top-level directory nrfu_tests
Use markers nrfu_test, security
Use Test ID: NRFU5.5
From the output of  'show banner login' and verifying that the login banner is correct.
#436 
- - [x] Other (NRFU Testcase)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Unit Tests:
- Tested for all the …
> Issue-436:Convert Pytest-CVP Login Banner test case to Vane #436

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_misc_show_commands.py
Converted test_misc_show_commands.py as per the vane style guide along with that updated following files.
test_definition.yaml: Updated test def with testcase NRFU3.1
test_definition.yaml.j2 : Updated J2 with testcase NRFU3.1
Verified misc show commands are ran successfully on the device.
https://github.com/aristanetworks/vane/issues/429
- - [x] Other (nrfu test development)
- - [ ] Easy
- - [x] Medium
- - [ ] Hard 
Unit tests and reports :
1) Pass_case : Verified that  misc show commands are executed …
> issue_429: Converted Pytest-CVP misc show test case to Vane #429

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_routing_multi_agent.py
test_definition.yaml: Updated test def with testcase NRFU4.4
test_definition.yaml.j2: Updated J2 with testcase NRFU4.4
test_routing_multi_agent.py: Added python file for testcase NRFU4.4
Running 'show ip route summary' command and verifying multi agent routing model protocol is configured and operational on the device
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Passed reports when multi agent enabled on device
[report_passed.docx](https://github.com/aristanetworks/vane/files/12483586/rep …
> Added TC for NRFU4.4 Multi agent routing protocol functionality

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_system_hardware_cooling_status.py
Converted test_system_hardware_cooling_status.py  as per the vane style guide along with that updated following files.
Use Test ID: NRFU6.2
test_definition.yaml: Updated test def with testcase  NRFU6.2
test_definition.yaml.j2: Updated J2 with testcase  NRFU6.2
pytest.ini: Added marker nrfu_test and system
nrfu_tests/nrfu_tests/test_system_hardware_cooling_status.py: Added testcase for NRFU6.2
masterdef.yaml: Updated master def file with global filter.
Test case should be skipped if vEOS : Added condition in test case.
This testcase will verify the System cooling status should be 'coolingOk' in 'show system environment cooling' command output. If cooling status is not found test case will fail.
#441 
- - [ ] New feature …
> Issue-441:Convert Pytest-CVP Cooling Status test case to Vane #441

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_hardware_power_supply_voltage_status.py
test_definition.yaml: Updated test def with testcase NRFU6.10.
test_definition.yaml.j2: Updated J2 with testcase NRFU6.10.
master_def.yaml: Updated master def with testcase NRFU6.10.
test_security_rp_ssh_access_list.py: Added python file for testcase NRFU6.10.
This testcase will verify the power voltage sensor status in  `show system environment power voltage` command output if power supply sensors are not found test case will fail with assertion error. If device platform is vEOS the test case will skip.
#449 
- - [ ] Breaking change (fix or feature that would …
> issue-449: Automated test case for Convert Pytest-CVP Power Supply Voltage test case to Vane

- .github/workflows/cvp-extension-builder.yml
* .github/workflows/cvp-extension-builder.yml - add workflow_dispatch trigger - this should create a button that lets us manually start the workflow from the browser.
N/A
N/A
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Needs to be in default branch to work
N/A
N/A
> Add manual trigger for building CVP extension

- nrfu_tests/master_def.yaml
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_routing_evpn_l2vni_imet.py
test_definition.yaml: Updated test def with testcase NRFU4.3
test_definition.yaml.j2: Updated J2 with testcase NRFU4.3
master_def.yaml: Updated master def file for NRFU4.3
test_routing_evpn_l2vni_imet.py: Added python file for testcase NRFU4.3
Running `show bgp evpn summary` command and verifying EVPN is configured on the device also
Running `show interfaces <vxlan interface>` command and verifying L2 VNIs are configured on the device
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Passed …
> Added TC for NRFU4.3 EVPN L2 VNI routes details verification

- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_security_rp_username_password.py
Converted test_security_rp_username_password.py as per the vane style guide along with the updated following files.
test_definition.yaml: Updated test def with testcase NRFU5.8
test_definition.yaml.j2: Updated J2 with testcase NRFU5.8
nrfu_tests/test_security_rp_username_password.py: Added converted testsuite file for testcases NRFU5.8
From the output of show running-config all section ^username, verified that the all username configured with a password , if usernames are not found then testcase will skip.
#439 
- - [ ] This change requires a documentation …
> Issue_439: Convert Pytest-CVP Username No Password test case to Vane #439

- nrfu_tests/master_def.yaml
- nrfu_tests/test_base_services_dns.py
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_dns_base_services.py
* test_definition.yaml: Updated test def with testcase NRFU1.1
* test_definition.yaml.j2: Updated J2 with testcase NRFU1.1
* nrfu_tests/nrfu_tests/test_base_services_dns.py: Added testcase for NRFU1.1
* masterdef.yaml: Updated master def file with global filter and testcase data
#419 
- - [x] Other (NRFU Testcase)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Unit Testing:
1. Tested the testcase for pass …
> Issue-419: Convert Pytest-CVP DNS test case to Vane

- install_vane.sh
* install_vane.sh: made the changes listed in title. Installation of poetry was being problematic via pip, so used pipx instead as that is the standard way to install Python CLI applications globally while still isolating them in virtual environments.
Installation of poetry: https://github.com/aristanetworks/vane/pull/574/files#r1353269245
#573 
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Sets up Vane correctly in a Linux subsystem
- - [X] Pass
- - [ ] Fail
> Added message formatting, error handling and changed installation of poetry in script

- .github/workflows/development-ci.yml
* .github/workflows/development-ci.yml
* moved coverage check into a separate job that is dependent upon the unittests job
* if unittests job fails, coverage check job does not run
* if unit tests pass, coverage is captured and stored in GITHUB_OUTPUT which is accessible in the coverage check job
After this change is merged, we will update our PR requirements so that all 3 checks must pass (validate, unittests, coverage) with the coverage being optional since we are not at the goal yet.
N/A
Fixes #535 
- - [ ] …
> Separate unit tests and coverage check in development CI workflow

- install_vane.sh
* install_vane.sh: removed logic which tried installing requirements, now script errors out and asks the user to install those before trying to setup Vane. Installation of poetry is done using curl.
Installation of poetry: Point (4) : https://github.com/aristanetworks/vane/blob/a361ee9d37bfe023e668f4d5af86994b8354d2c3/install_vane.sh#L57
#588 
- - [X] Other : Refactoring of logic to handle permission issues & installation of poetry logic changed
- - [ ] Easy
- - [X] Medium
- - [ ] Hard 
Tested on Ubuntu, CentOs …
> Simplified the Installation script to error out if requirements are not installed

- .github/workflows/cvp-extension-builder.yml
- Dockerfile.build-CVP
- resources/vane-cvp-install.sh
- resources/vane-cvp-start.sh
- resources/vane-cvp-uninstall.sh
These changes address installation and uninstallation difficulties with the Vane CVP extension, simplifying the process for the user. The zip file that is downloaded from the Vane repository now contains a directory that includes the Vane RPM package, plus 3 shell scripts that are used for handling the Vane CVP extension. 
The user simply needs to download the zip file and copy it to the CVP host in the root user's home directory (for simplicity), then log into the host as root user and run the command
`unzip vane-cvp-<version>-rpm.zip && tar xzvf vane-cvp*.tgz`
to extract the contents. After that, a directory will have been created containing the RPM and the 3 shell scripts.
Within the directory, running `./vane-cvp-install.sh` will install the Vane CVP extension, start it running, and …
> Automate Vane CVP extension installation/uninstallation

- vane/tests_tools.py
* File 1 and corresponding changes
vane/tests_tools.py: 
I dont think we want to rerun commands as text if json is not available. However if strict is not set to True then, pyeapi passes each command in separate call so as to determine if the cmd failed because of json formatting. Thus the second command losses the context set by first command. 
#613 
Using pyeapi APIs with proper context here.
- - [x] Easy
- - [ ] Medium
- …
> Issue #613: Setting strict to True, which was splitting the cmds being run through pyeapi

- tests/unittests/test_vane_cli.py
- vane/config.py
- vane/vane_cli.py
* vane_cli.py and config.py: removed the --environment flag
* test_vane_cli.py: refactored the relevant test cases
#611 
- - [X] Other : Refactor
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
All the test cases pass
- - [X] Pass
- - [ ] Fail
Updated documentation to not have --environment flag in CLI reference guide
> Removed --environment flag

- nrfu_tests/conftest.py
- sample_network_tests/conftest.py
- vane/fixtures.py
* sample_network_tests/conftest.py: Removed html customization logic to fixtures.py (within vane framework)
* nrfu_tests/conftest.py: Removed html customization logic to fixtures.py (within vane framework)
* fixtures.py : added report customisation logic along with newer logic to add column for test id"
New function: Retrieving test id from test defs: https://github.com/aristanetworks/vane/blob/d8dec32012ba6dd5e76e5f411ffef9be48cbc385/vane/fixtures.py#L343
https://github.com/aristanetworks/vane/issues/349
- - [ …
> Added test id to html report

- tests/unittests/test_tests_tools.py
- tests/unittests/test_vane_cli.py
- vane/tests_tools.py
- vane/vane_cli.py
* tests_tools.py: removed generate_duts_file method called from vane_cli to generate duts from topo
* vane_cli.py: removed create_cuts_from_topo method called when --generate-duts-from-topo flag is used
* modified the tests for these two modules
#571 
- - [X] Refactor
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
All tests pass:
- - [X] Pass
- - [ ] Fail
> Removed generate-duts-from-topo functionality and modified tests

- vane/gen_configs_from_avd.py
* gen_configs_from_avd.py: avd config info did not have a field called vxlan_interfaces but instead vxlan_interface
#203 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
@shachiagarwal has tested with the change in the customer environment
- - [X] Pass
- - [ ] Fail
> Refactored vxlan_interfaces to vxlan_interface in gen_configs_from_avd

- vane/report_client.py
* report_client.py: Changed the logic that checked for skip condition while counting # of skipped. We were using dut["testcase_result"] which actually is a boolean value and would be set to False for both a failed and skipped test case. Changed the logic to use dut["skip"] and dut[testcase_result"] field instead.
@kgrozis-arista I went through the different methods to make sure our checks for SKIP are correct, I think these 2 places got missed in the original PR, but should be good now. Can you also double check for any other place that we may have missed so there are no hidden bugs anymore :) 
#584 
- - [ ] Breaking change (fix or feature that would cause existing …
> [FIX]: for bug involving incorrect skip condition check in docx reports

- sample_network_tests/aaa/test_definition.yaml
- sample_network_tests/api/test_definition.yaml
- sample_network_tests/cpu/test_definition.yaml
- sample_network_tests/daemon/test_definition.yaml
- sample_network_tests/dns/test_definition.yaml
- sample_network_tests/environment/test_definition.yaml
- sample_network_tests/extension/test_definition.yaml
- sample_network_tests/filesystem/test_definition.yaml
- sample_network_tests/host/test_definition.yaml
- sample_network_tests/interface/test_definition.yaml
- sample_network_tests/lldp/test_definition.yaml
- sample_network_tests/log/test_definition.yaml
- sample_network_tests/memory/test_definition.yaml
- sample_network_tests/ntp/test_definition.yaml
- sample_network_tests/system/test_definition.yaml
- sample_network_tests/tacacs/test_definition.yaml
- sample_network_tests/users/test_definition.yaml
- sample_network_tests/ztp/test_definition.yaml
* test_definition.yaml of all sample network test cases
Did not add test case id's to the tests in vane_system_tests, since those are not network tests, should we add id's for those as well? Also should the vane_system_tests be placed in sample network tests folder?
#601 #136 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
The reports generated now have ID's. However the order of test cases is not maintained in the reports, is that expected, can see below: (10->18->12)
- - [X] Pass
- - …
> Added test id to sample network tests

- .github/workflows/cvp-extension-builder.yml
- conf/cvpi/conf/components/vane-cvp.multinode.yaml
- conf/cvpi/conf/components/vane-cvp.singlenode.yaml
- resources/vane-cvp-install.sh
- resources/vane-cvp-uninstall.sh
CVP 2023.2+ removed docker and replaced with containerd, which caused some issues with the Vane CVP extension. These changes address those issues, plus a few minor enhancements to the build process.
* conf/cvpi/conf/components/vane-cvp.multinode.yaml - remove dependency on docker (this still works on older versions of CVP where docker is used)
* conf/cvpi/conf/components/vane-cvp.singlenode.yaml - remove dependency on docker as above
* .github/workflows/cvp-extension-builder.yml - rework the tagging section to add a 'provisional' tag when building a branch other than main or develop. Also adds a timestamp to the directory structure, so the download is clear when it was built. The RPM file name stays unchanged (no timestamp or provisional tag either way).
* resources/vane-cvp-install.sh - …
> Update Vane-CVP build for 2023.2+ versions

- nrfu_tests/test_routing_evpn_l2vni_imet.py
* nrfu_tests/test_routing_evpn_l2vni_imet.py
Changed logic to skip switches that do not have EVPN tenants.  Previously, test cases failed these switches.
NRFU 4.3 - test case test_routing_evpn_l2vni_imet is broken #663
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Yes: https://github.com/aristanetworks/ps-demos/actions/runs/8236888452
See above
- - [x] Pass
- - [ ] Fail
N/A
> skip test_routing_evpn_l2vni_imet if evpn not configured

- vane/tests_tools.py
… to run tests on
* tests_tools.py: added logic for exiting Vane when no duts are available. This error is more likely to happen when running Vane on CVP instance in case the duts are in undefined container since we filter out duts which are in undefined container.
#684 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
All current tests pass and in case 0 duts are found the error gets thrown correctly and Vane exits out
- - [X] Pass
- - [ ] Fail
> Adding logic for graceful failure handling when no duts are available

- resources/vane-cvp-uninstall.sh
Older versions of CVP use docker, newer versions use containerd which uses the nerdctl command to handle containers.
During uninstallation, we remove the containers related to the Vane-CVP extension. We need to check whether we are working with docker or nerdctl before doing the container removal. In the steps, we assume we are using nerdctl, then check for the nerdctl command. If it doesn't exist, we switch to the docker command.
Operation should behave as explained above
Hotfix - no related issue
- - [ ] …
> Update Vane-CVP uninstall script for docker vs nerdctl command

- nrfu_tests/test_hardware_power_supply_voltage_status.py
- nrfu_tests/test_system_hardware_fan_status.py
- nrfu_tests/test_system_hardware_temperature.py
* nrfu_tests/test_hardware_power_supply_voltage_status.py
* nrfu_tests/test_system_hardware_fan_status.py
* nrfu_tests/test_system_hardware_temperature.py
Arista 7010 switch does not have power supply sensors.  Corrections are made to skip the switch if needed or reduce the testing requirements.
https://github.com/aristanetworks/vane/issues/678
https://github.com/aristanetworks/vane/issues/677
None
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [x] Pass
- - [ ] Fail
> 678 nrfu611 test system temperature sensors

- nrfu_tests/master_def.yaml
- nrfu_tests/test_base_services_ntp_association.py
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- Updated nrfu_tests/master_def.yaml with NRFU1.2 testcase changes
- Updated nrfu_tests/test_base_services_ntp_association.py  with the support for single ntp server
- Updated nrfu_tests/test_definition.yaml with NRFU1.2 testcase changes
-Updated nrfu_tests/test_definition.yaml.j2 with NRFU1.2 testcase changes
#660 
- - [ ] Easy
- - [x] Medium
- - [ ] Hard 
Include before and …
> Issue_660: Fixed NRFU1.2 NtpAssocitionsTests - Tests incorrectly failing

- nrfu_tests/test_system_hardware_flash_free_space.py
* 668-nrfu66-test_system_hardware_flash_free_space-is-broken
New try/except block for checking peer supervisor.  If peer command, fails the test case can determine there is no supervisor.
NRFU6.6 test_system_hardware_flash_free_space is broken #668
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Network services review output
- - [x] Pass
- - [ ] Fail
> 668 nrfu66 test system hardware flash free space is broken

- nrfu_tests/test_system_hardware_coredump.py
* nrfu_tests/test_system_hardware_coredump.py
Ignore minidump directory.  Seems to be a software artifact in EOS that isn't used.
https://github.com/aristanetworks/vane/issues/667
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
https://github.com/aristanetworks/ps-demos/actions/runs/8238515372
- - [x] Pass
- - [ ] Fail
> nrfu6.3 ignores minidump directory

- nrfu_tests/test_routing_evpn_l2vni_imet.py
test_routing_evpn_l2vni_imet.py: Updating skip functionality and fixing type error in NRFU4.3
https://github.com/aristanetworks/vane/issues/581
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Passed reports when EVPN routes are advertised for all VNIs
[report_passed.docx](https://github.com/aristanetworks/vane/files/12916232/report_passed.docx)
Failed reports when test criteria does not met( tested using hardcoded output)
[report_failed.docx](https://github.com/aristanetworks/vane/files/1291 …
> Updating skip functionality and fixing type error in NRFU4.3 test_routing_evpn_l2vni_imet testcase

- nrfu_tests/master_def.yaml
- nrfu_tests/test_definition.yaml
- nrfu_tests/test_definition.yaml.j2
- nrfu_tests/test_interfaces_non_arista_optics.py
* nrfu_tests/master_def.yaml
* nrfu_tests/test_definition.yaml
* nrfu_tests/test_definition.yaml.j2
* nrfu_tests/test_interfaces_non_arista_optics.py
Provide users ability to add approved 3rd party optics to master definitions.  Logic incorporates these optics into evaluation of the DUT.
NRFU2.5 - test_interfaces_non_arista_optics #700
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Verified with network service3s
- - [x] Pass
- - [ ] Fail
> enhanced nrfu2.5 for user defined approved optics

- nrfu_tests/test_base_services_tacacs.py
Updated nrfu_tests/test_base_services_tacacs.py testcase with skip testcase enhancement(NRFU1.4)
https://github.com/aristanetworks/vane/issues/706
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- - [ ] Pass
- - [ ] Fail
If it fails, explain the reason and whether or not …
> Issue_706: Updated skip enhancement: nrfu_tests/test_base_services_tacacs.py(NRFU1.4)

- nrfu_tests/test_bgp_peers_state.py
- nrfu_tests/test_definition.yaml.j2
Skip enhancement: nrfu_tests/test_bgp_peers_state.py(NRFU4.2)
Skip enhancement: nrfu_tests/test_bgp_peers_state.py(NRFU4.2)
Updated description change in :  nrfu_tests/test_definition.yaml.j2 file.
NRFU4.2
https://github.com/aristanetworks/vane/issues/713
- - [ ]  New feature (non-breaking change which adds functionality)
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
Ensure current test cases pass and …
> Issue-713:Skip enhancement: nrfu_tests/test_bgp_peers_state.py(NRFU4.2)

- vane/tests_client.py
vane/tests_client.py -
Added traceback as parameter in definitions.yaml. The default behavior for traceback is to not print any tracebacks in html reports. To enable traceback printing in html reports, add following line to definitions.yaml file:
traceback: true
Closes #659 
- - [X] This change requires a documentation update
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Here is the html report without traceback in …
> Issue-659: Dont print traceback by default

- tests/unittests/fixtures/fixture_duts_no_role.yaml
- tests/unittests/test_tests_tools.py
- vane/tests_tools.py
* tests_tools.py -> add role to be None in case role is not present in duts.yaml, so now Vane does not fail if role field is not present in duts file
* test_tests_tools.py -> added tests to verify the above change
* fixture_duts_no_neighbors.yaml -> fixture added for testing wherein duts do not have role
https://github.com/aristanetworks/vane/issues/463
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
Ensured current test cases pass and included newer test cases:
- - [X] Pass
- - [ ] …
> Make role field optional in duts.yaml

- tests/unittests/test_fixtures.py
- tests/unittests/test_tests_tools.py
* test_tests_tools.py
* test_fixtures.py
Removed logging from these 2 files to ensure consistency across all unit tests (none of them have logs, whether we want logs or not might be another conversation :))
Realized the current logs in these test cases were not actually logging to any file since they were using the build in logging module instead of vane logging. So resolved that bug by converting the logs into prints.
#640 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
- - [X] Pass
- …
> Removed logging from unit tests

- tests/unittests/test_tests_tools.py
* test_tests_tools.py: Added tests (2) for verify_show_cmd when list of show_cmds is passed, one wherein the verification passes and one where verification fails
https://github.com/aristanetworks/vane/issues/626
#620 should be merged after this PR is merged into the PR branch for 620
This PR needs to be merged first as it refactors verify_show_cmd to accept a list of show commands and not just a single string
Context: https://github.com/aristanetworks/vane/pull/620/files#r1461382392
- - [X] Other : Testing
- - …
> Added test for verify_show_cmd when list of show cmds are passed

- vane/report_client.py
Fixed bug : #742 
* report_client.py: added logic to not continue when there are no test_case results. This was being handled for default test case reports but not for custom test case reports
#742 
- - [X] Easy
- - [ ] Medium
- - [ ] Hard 
BEFORE:
AFTER
- - [X] Pass
- - [ ] Fail
> Handle graceful Vane exit when no devices are selected to run Vane tests

- .pylintrc
- tests/unittests/fixtures/definitions_nrfu_custom_expected.yaml
- tests/unittests/fixtures/definitions_nrfu_default_expected.yaml
- tests/unittests/test_nrfu_client.py
- vane/nrfu_client.py
- vane/report_client.py
* nrfu_client.py - ask whether user wants detailed report
* report_client.py - depending on `generate_only_summary_report` in definitions.yml - generate only summary docx reports
None
N/A
closes #658 
- - [x] Easy
- - [ ] Medium
- - [ ] Hard 
- Unit tested
- Tested functionality with `vane --nrfu` option and with just plain `vane` too
Summary report - 
[report_2404060737.docx](https://github.com/aristanetworks/vane/files/1489 …
> Issue #658: Add support for only generating summary docx reports

- vane/tests_tools.py
* vane/tests_tools.py - Updated file with a utils to validate a XML character, 
- Added utils to validate the XML characters in the command output
- Added check to format the command output first and then pass it for evidence section of docx report.
#638 
- - [ ] Easy
- - [x] Medium
- - [ ] Hard 
Note: Tested all the reports with hardcoded output.
**Reports before adding the fix for the invalid characters in the command output** …
> Issue_638: Added fix for XML character in the command output.
